### ISSUE TITLE
LaGrit permission denied

### ISSUE THREAD

**Issue by yihao-ai** [dfnWorks/dfnWorks-Version2.0#15]
Hi,

I have installed dfnworks 2.1 and requested packages (pflotran and LaGriT) on the system, and I was trying to run the 4_user_defined_rectangles example, but I got an error in Meshing Networking Using LaGriT stage: 

`sh: 1: /home/yihao/LaGriT: Permission defined

unable to open file: id_tri_node_CPU1.list

MESH CHECKING HAS FAILED!!!!`

I have attached my paths.py file, I wonder whether the error was caused by my path setting, specifically for path for the LaGriT executable. Not sure if I set up correctly - I do not find any bin folder???

Many Thanks,

YIHAO
[paths.py.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/2545694/paths.py.txt)

**Comment by hymanjd** [comment]
It looks like you are point to the LaGriT directory not the compiled executable. Should be in LaGriT/src/

**Comment by yihao-ai** [comment]
> It looks like you are point to the LaGriT directory not the compiled executable. Should be in LaGriT/src/

Thanks hymanjd,

I have changed the path to /LaGriT/src/lagrit, however I still have this error when running the test example - I have attached the log error. 
[logerr.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/2547031/logerr.txt)


Not sure what actually causes the error? Wonder if it is because I did not build the LaGriT properly? It seems the tests did not pass after building. 
[lagrit_log.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/2547032/lagrit_log.txt)

Thanks,

**Comment by hymanjd** [comment]
When you go into /LaGriT/src/ can you run lagrit on its own? @daniellivingston any ideas?
J

**Comment by daniellivingston** [comment]
@yihaoFu , looking at your test log, I see this error on every test:

```
error while loading shared libraries: libexodus.so.2: cannot open shared object file: No such file or directory
System exit: 32512
```

I suspect that if you try to launch LaGriT by itself you will see the same error.
The issue is that LaGriT is trying to source the shared library `libexodus.so.2` and `ld` cannot find it, so it throws an error.
You have this library (I believe it's in `LaGriT/TPL/`), though the linker cannot find it unless the path to the Exodus libraries are appended to `LD_LIBRARY_PATH`.

For this reason I strongly suggest rebuilding LaGriT as a static executable, particularly for people using it in dfnWorks.

**Comment by yihao-ai** [comment]
I have rebuilt LaGriT as a static executable. 

- if I just use automatic build for LaGriT, by type `./install.sh --static`, it shows the error: 
`/usr/bin/ld: cannot find -lnetcdf`
[static_error.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/2552369/static_error.txt)

- So I build Exodus first, can then install LaGriT by type `.install.sh --static --exodus=/home/yihao/seacas/lib` Not sure if I give correct path???
Then I build LaGrit, in the test log, 1 out of 38 failed, however I able to successfully run lagrit in /LaGriT/src/ 
[lagrit_log.txt](https://github.com/dfnWorks/dfnWorks-Version2.0/files/2552393/lagrit_log.txt)

However I still get the same error saying:
`sh: 1: 1/home/yihao/LaGriT: Permission denied
unable to open file: id_tri_node_CPU1.list
MESH CHECKING HAS FAILED!!!!`

BTW: do I need parse LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=/home/yihao/seacas/lib` ??? because at the moment when I type `echo $LD_LIBRARY_PATH` it shows nothing.

Many Thanks for your help,

**Comment by daniellivingston** [comment]
Can you run

```bash
ldd /path/to/LaGriT/binary
```

and display the results here?

**Comment by yihao-ai** [comment]
> Can you run
> 
> ```shell
> ldd /path/to/LaGriT/binary
> ```
> 
> and display the results here?

Hi Daniel,

May I ask where to find the 'binary' file? there is no folder or file called binary inside LaGriT folder. but I have print the ldd /home/yihao/LaGriT/src/lagrit below, not sure if it is helpful:

`linux-vdso.so.1 (0x00007fff92df3000)

    libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f424137b000)  

    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4240fdd000)

    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4240c54000)

    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4240a3c000)

    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f424064b000)

    libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f424040b000)

    /lib64/ld-linux-x86-64.so.2 (0x00007f4259e64000)`

**Comment by yihao-ai** [comment]
Still stuck in this problem.... Any advice?

**Comment by daniellivingston** [comment]
Hi @yihaoFu , sorry for the delay. You are correct that by 'binary' I meant your LaGriT executable. I expected to see `ldd` display Exodus dependencies, which might have meant the problem was a linking issue. That would have been fixed by, like you pointed out, calling `export LD_LIBRARY_PATH=/home/yihao/seacas/lib`.

Can you try to directly run `./home/yihao/LaGriT/src/lagrit`? If you are still seeing `sh: 1: /home/yihao/LaGriT: Permission denied` in PyDFNWorks, you might try running the command: `chmod a+x /home/yihao/LaGriT/src/lagrit`.

You could also try running `import os; os.system("/home/yihao/LaGriT/src/lagrit")` in the Python interpreter, as that would be a rough proxy for getting the same error as in PyDFNWorks:

`dfnWorks/pydfnworks/pydfnworks/run_meshing.py`:40
```
        cmd_check = os.environ['connect_test'] + 'ConnectivityTest' \
        + ' intersections_CPU%d.inp' \
        + ' id_tri_node_CPU%d.list ' \
        + ' mesh_%d.inp' \
        + ' %d'
        cmd_check = cmd_check%(cpu_id,cpu_id,fracture_id,fracture_id)
        failure = os.system(cmd_check)
        if failure > 0:
            print("MESH CHECKING HAS FAILED!!!!")
```

**Comment by yihao-ai** [comment]
> Hi @yihaoFu , sorry for the delay. You are correct that by 'binary' I meant your LaGriT executable. I expected to see `ldd` display Exodus dependencies, which might have meant the problem was a linking issue. That would have been fixed by, like you pointed out, calling `export LD_LIBRARY_PATH=/home/yihao/seacas/lib`.
> 
> Can you try to directly run `./home/yihao/LaGriT/src/lagrit`? If you are still seeing `sh: 1: /home/yihao/LaGriT: Permission denied` in PyDFNWorks, you might try running the command: `chmod a+x /home/yihao/LaGriT/src/lagrit`.
> 
> You could also try running `import os; os.system("/home/yihao/LaGriT/src/lagrit")` in the Python interpreter, as that would be a rough proxy for getting the same error as in PyDFNWorks:
> 
> `dfnWorks/pydfnworks/pydfnworks/run_meshing.py`:40
> 
> ```
>         cmd_check = os.environ['connect_test'] + 'ConnectivityTest' \
>         + ' intersections_CPU%d.inp' \
>         + ' id_tri_node_CPU%d.list ' \
>         + ' mesh_%d.inp' \
>         + ' %d'
>         cmd_check = cmd_check%(cpu_id,cpu_id,fracture_id,fracture_id)
>         failure = os.system(cmd_check)
>         if failure > 0:
>             print("MESH CHECKING HAS FAILED!!!!")
> ```

Hi @daniellivingston, thanks for your suggestions - I can run ./lagrit successfully. 

I have add `export LD_LIBRARY_PATH=/home/yihao/seacas/lib`, and run the command: `chmod a+x /home/yihao/LaGriT/lagrit`; however, when I run the 4_user_defined_rectangles example, it still shows the same error.

```sh: 1: /home/yihao/LaGriT: Permission denied

Unable to open file: id_tri_node_CPU1.list

MESH CHECKING HAS FAILED!!!!

Fracture number 1        running on Process-1

sh: 1: /home/yihao/LaGriT: Permission denied

Unable to open file: id_tri_node_CPU2.kust

MESH CHECKING HAS FAILED!!!!

Fracture number 2        running on Process-2
```

Have no idea what to do.... maybe try to build everything from scratch??

Thanks, YIHAO

**Comment by hymanjd** [comment]
What do you have in your paths.py file for os.environ['lagrit_dfn'] ?

 It should be 
os.environ['lagrit_dfn'] = /home/yihao/LaGriT/lagrit
 
Did you also rerun setup.py install --user after you corrected the paths.py file?

**Comment by yihao-ai** [comment]
> What do you have in your paths.py file for os.environ['lagrit_dfn'] ?
> 
> It should be
> os.environ['lagrit_dfn'] = /home/yihao/LaGriT/lagrit
> 
> Did you also rerun setup.py install --user after you corrected the paths.py file?

I forgot to rerun setup.py install.... Now everything works fine, very appreciate for your help!

Thanks, Yihao

**Comment by hymanjd** [comment]
Happy to hear it worked. I'm going to close this thread.

**Comment by hymanjd** [comment]
close

**Comment by hymanjd** [comment]
closes issue #15
